name: Build and Release macOS App

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-universal:
    name: Build macOS Universal App
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install -g @tauri-apps/cli

      - name: Set up Rust targets
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - name: Build universal Tauri app
        run: npm run tauri build -- --target universal-apple-darwin

      - name: Zip the app bundle
        run: |
          cd src-tauri/target/universal-apple-darwin/release/bundle/macos
          ditto -c -k --keepParent Support.app Support.zip

      - name: Upload artifact (universal)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Support-universal
          path: src-tauri/target/universal-apple-darwin/release/bundle/macos/Support.zip
          retention-days: 7
          if-no-files-found: error

  tag-latest:
    name: Update 'latest' tag
    runs-on: ubuntu-latest
    needs: [build-universal]

    steps:
      - uses: actions/checkout@v3

      - name: Force-push 'latest' tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git tag -f latest
          git push origin -f latest

  update-release:
    name: Upload to GitHub Release
    runs-on: macos-latest
    needs: [tag-latest]

    steps:
      - name: Download universal artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: Support-universal
          path: artifacts

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Support App (Latest)
          body: |
            This is the latest signed and notarised build of the Support app.

            Built as a universal binary (Intel + Apple Silicon).

            Delivered automatically from the `main` branch.
          files: |
            artifacts/Support.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}