name: Build and Release macOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add Rust targets for universal binary
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - name: Install dependencies
        run: |
          npm install
          npm install -g @tauri-apps/cli

      - name: Build Tauri app (universal)
        run: npm run tauri build -- --target universal-apple-darwin

      - name: Zip the .app
        run: |
          cd src-tauri/target/universal-apple-darwin/release/bundle/macos
          ditto -c -k --keepParent Support.app Support.zip
          ls -lh

      - name: Check that zip exists
        run: |
          if [ ! -f src-tauri/target/universal-apple-darwin/release/bundle/macos/Support.zip ]; then
            echo "❌ Support.zip not found."
            exit 1
          else
            echo "✅ Support.zip found, proceeding to tag and release."
          fi

      - name: Create or update 'latest' tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin
          git tag -f latest
          git push origin latest --force

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest
          files: |
            src-tauri/target/universal-apple-darwin/release/bundle/macos/Support.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}